### ISSUE TITLE
Flux GitHub commit status updates

### ISSUE THREAD

**Issue by Stephen-ONeil** [PHACDataHub/cpho-phase2#145]
Add a Flux notification controller to [set Flux reconciliation status on GitHub commits](https://fluxcd.io/flux/components/notification/providers/#git-commit-status-updates). Additional info [here](https://fluxcd.io/flux/monitoring/alerts/#git-commit-status).

**Comment by vedantthapa** [comment]
If we're configuring this, do you think we should disable slack alerts? 

Looks like they'll be sending out the same information (only for kustomization events though). Alternatively, we can have both with one set to `info` level and the other at an `error` level. My suggestion would be to keep gh commit status to `error` so that noisy events such as _dependency do not meet ready condition..._ don't keep toggling status changes.

thoughts?

**Comment by Stephen-ONeil** [comment]
GitHub status badges have more information, since they also tell us what commit it was that failed (and also leave a history of good and bad commits on main). GitHub notifications are kind of easy to miss though, in my experience. I think duplication on slack is fine since it'll increase the chances someone notices the problem ASAP.

I'm also all for continuing to tune the slack messages though! Not sure there's that many options available to us, but it's worth spending some time looking in to.
